baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Tertium Quid: post-modern magical consciousness'

theme = "hugo-tufte"

uglyURLs = false
	
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

# [[menu.main]]
# name = "Articles"
# url = "/articles/"
# weight = 3

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 4

[[menu.sidebar]]
identifier = "philosophy"
name = "philosophy"
url = "/philosophy/"
weight = 1

[[menu.sidebar]]
parent = "philosophy"
name = "spiritual frameworks"
url = "/articles/spiritual_frameworks/"
weight = 1

[[menu.sidebar]]
parent = "philosophy"
name = "Thomas Nagel"
url = "/articles/Thomas_Nagel/"
weight = 2

[[menu.sidebar]]
identifier = "science"
name = "science"
url = "/science/"
weight = 2

[[menu.sidebar]]
parent = "science"
name = "scientific method"
url = "/articles/scientific_method"
weight = 2

[[menu.sidebar]]
parent = "science"
name = "classical worldview"
url = "/articles/classical_worldview/"
weight = 1

[[menu.sidebar]]
identifier = "practices"
name = "practices"
url = "/practices/"
weight = 3


[[menu.sidebar]]
parent = "practices"
name = "life organizing principles"
url = "/articles/life_organizing_principles/"
weight = 1

[[menu.sidebar]]
parent = "practices"
name = "Phoenix Affirmations"
url = "/articles/phoenix_affirmations/"
weight = 2

[[menu.sidebar]]
identifier = "energy"
name = "energy"
url = "/energy/"
weight = 3


[[menu.sidebar]]
parent = "energy"
name = "fusion illusion"
url = "/articles/fusion_illusion/"
weight = 1

[[menu.sidebar]]
identifier = "speculations"
name = "speculations"
url = "/speculations/"
weight = 4

[[menu.sidebar]]
parent = "speculations"
name = "uncivilization"
url = "/articles/dark_mountain/"
weight = 1
